### ISSUE TITLE
Get bunch folder from preferences

### ISSUE THREAD

**Issue by ttscoff** [kjaymiller/Bunch_Alfred#2]
The user has the ability to change where Bunch stores its files, so you need to be able to follow that preference. You can retrieve the location of the current folder using:

     defaults read com.brettterpstra.bunch configDir

The command takes a second to run, which can put an annoying delay in script execution, but I don't currently have a better solution.

**Comment by kjaymiller** [comment]
@ttscoff tried doing this on my system locally and ran into this error ![https://dsc.cloud/kjmScreenshots/pb-Q6A4nHxdOv.png] Would love to know how to resolve this issue if the user runs into it!

**Comment by kjaymiller** [comment]
I was able to pull the information and have it set as a environment variable for Alfred. This can be updated using `bsettings:refresh`
