### ISSUE TITLE
Same issue as previous report

### ISSUE THREAD

**Issue by mikeerickson** [kjaymiller/Bunch_Alfred#6]
@kjaymiller I am creating a new issue since you closed the other issue and have disabled the ability to reopen an issue

I have installed the latest version (https://github.com/kjaymiller/Bunch_Alfred/issues/5) and I am still experiencing the same issue as originally reported.  

I am not sure if there is something else required other than downloading updated extension and reinstalling

**Comment by kjaymiller** [comment]
Just to confirm I'm not missing something simple can you provide provide the following information:

In System:

- [ ] Confirm Bunch is running when you try to execute. 

in Alfred Preferences -> Workflow -> Bunch:
-  [ ] enable debug on 
- [ ] try the workflow and log the debug

![Debug Mode](https://user-images.githubusercontent.com/8632637/113927496-6d595800-97a2-11eb-891f-d4b0730b13e6.png)
 information

My assumption is that there may be an issue with the bunch CLI being out of date or not running properly, but I would need output to troubleshoot.

**Comment by mikeerickson** [comment]
@kjaymiller What do you want me to look for in the debug information?  I have enabled debugging and can see the logging occur, but not sure what you want with the information.

I know for sure Bunch is running

![image](https://user-images.githubusercontent.com/183153/113940393-3a1ec500-97b2-11eb-803b-c4654588e7a4.png)

**Comment by kjaymiller** [comment]
What is your bunches folder set to?

**Comment by mikeerickson** [comment]
Default `~/bunches`

**Comment by kjaymiller** [comment]
Did you try to force refresh your bunches using `bsettings:refresh`?

**Comment by mikeerickson** [comment]
@kjaymiller I feel like we are grasping at straws at this point.  I just refreshed and still same results. 
At this point, I am losing hope that this will actually work, and I will just continue using Bunches as I do now (through the menubar app)

**Comment by kjaymiller** [comment]
I can tell you what the issue is but what I can't do is tell you the exact way to fix it without the information and knowing what you've done.

It sounds very much like the `configDir` in the CLI properties is not set properly. I did highlight how to reset it in the [README](https://github.com/kjaymiller/Bunch_Alfred/blob/main/README.md)

**Comment by mikeerickson** [comment]
@kjaymiller So, I have managed to get this working.  But curiously, the cli was not recognizing scripts until I executed `bunch -l` to list bunches.  After that, I was able to open a bunch from CLI *and* they now appear in Alfred.

I am really puzzled what the `bunch -l` did, but it is now working.

One thing that you mentioned was to run `bsettings:refresh` but that command did not work (where does `bsettings` come from)?

![image](https://user-images.githubusercontent.com/183153/114102116-9a2d6e00-987b-11eb-8a83-3f1ec6a301c2.png)

**Comment by kjaymiller** [comment]
@mikeerickson Brett mentioned that there's a cache that the cli pulls from by default.

the bunch workflow has some settings that can be triggered
<img width="1292" alt="bunch settings" src="https://user-images.githubusercontent.com/8632637/114200767-5e8db500-990a-11eb-818b-c1e29da7f357.png">

`bsettings:show_config` - shows the output of `ruby bunch.rb --show-config`
`bsettings:refresh` - sets the `configdir` as well as the bunches folder to the configDir defined in the bunches environment variables.

**Comment by mikeerickson** [comment]
Ah gotcha, I didn't notice those as my Alfred Settings screen was on my small MBP monitor and I didnt even notice that was there.  Now that I am aware of it, I see I could scroll it into view :-)

![image](https://user-images.githubusercontent.com/183153/114211324-59823300-9915-11eb-91d0-dae64b141268.png)
