### ISSUE TITLE
Despite reading the docs, no bunches visible

### ISSUE THREAD

**Issue by patowod** [kjaymiller/Bunch_Alfred#9]
Hi, thanks for making this. I really enjoyed your video on the newsletter bunch and thus found the workflow. Unfortunately, even though troubleshooting according to your instructions, the workflow fails to see my bunches. Debugging within Alfred I get the following result:

`ERROR: Bunch[Script Filter] Code 1: /Users/me/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/3FA0D5BA-0036-45CD-A7C2-A134CCECEAB1:0:13: script error: A identifier can’t go after this identifier. (-2740)`

If I run the workflow command to see my bunch folder it does return the correct folder. Any idea what might cause the issue? Both Bunch and your workflow are up to date. 

Thanks again for making this. Would be awesome if I get it to work.
All the best!

**Comment by hng** [comment]
I get the same error since updating to Bunch 1.4 and the latest version of the workflow.

**Comment by hng** [comment]
@patowod I've looked into this a bit more and got it to work again. Check #10

**Comment by patowod** [comment]
Very cool! 🎉 Thanks for the info @hng
